version: "3.8"

services:
  redis:
    image: my-redis-image
    container_name: Redis
    restart: always # 确保容器崩溃后自动重启
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - ./logs:/logs
    ports:
      - "881:881"  # 宿主机端口 110 映射到容器的 6379 端口
    command: ["redis-server", "/etc/redis/redis.conf"]
