# frps.ini                  # frps.ini 文件是Frps（反向代理服务器）的配置文件

[common]                   # [common] 段是共有的配置，应用于所有的Frps实例
bind_port = 7000            # 绑定的端口号，用于接收客户端的连接请求
token = q-org               # 客户端连接时需要验证的令牌（token），此处为示例，实际应用中需要更换为其他值
bind_addr = 0.0.0.0          # 绑定的IP地址，此处允许所有IP地址的连接请求
vhost_http_port = 180        # HTTP虚拟主机的端口号，用于提供HTTP代理服务

# vhost_https_port = 8443     # HTTPS虚拟主机的端口号，用于提供HTTPS代理服务，注释掉表示不启用
# subdomain_host = q.qio.wiki  # 用于定义子域名的主机，此处为示例，实际应用中需要更换为其他值

dashboard_addr = 0.0.0.0      # Dashboard服务的IP地址，用于提供Web控制面板服务，允许所有IP地址的连接请求
dashboard_port = 7500         # Dashboard服务的端口号，用于提供Web控制面板服务

# dashboard user and passwd for basic auth protect   # 用于启用基本认证保护的登录用户名和密码，此处为示例，实际应用中需要更换为其他值
dashboard_user = q-org        # Dashboard服务的登录用户名，此处为示例，实际应用中需要更换为其他值
dashboard_pwd = q-org          # Dashboard服务的登录密码，此处为示例，实际应用中需要更换为其他值

# dashboard TLS mode                             # Dashboard服务的TLS模式，注释掉表示不启用
dashboard_tls_mode = false                   # 是否启用TLS模式，false表示不启用，true表示启用
# dashboard_tls_cert_file = server.crt             # TLS证书文件路径，用于启用TLS模式时进行SSL/TLS握手
# dashboard_tls_key_file = server.key              # TLS密钥文件路径，用于启用TLS模式时进行SSL/TLS握手

log_file = ./frps.log                             # 日志文件的保存路径，用于记录Frps的运行日志

# log_level = trace, debug, info, warn, error        # 日志记录的级别，此处选择信息级别（info）作为示例，可根据需求调整
log_level = info                                   # 日志记录的级别，此处选择信息级别（info）作为示例，可根据需求调整

log_max_days = 3                                     # 日志文件保留的天数，超过该天数的日志将被自动删除

# 当日志文件是控制台时是否禁用日志的颜色（默认是false）
disable_log_color = false                            # 是否禁用日志的颜色（true表示禁用，false表示不禁用），此处为示例，实际应用中需要更换为其他值

# DetailedErrorsToClient defines whether to send the specific error (with debug info) to frpc. By default, this value is true.   # 是否将具体的错误（包含调试信息）发送给frpc客户端（默认是true）
detailed_errors_to_client = true                        # 是否将具体的错误（包含调试信息）发送给frpc客户端（true表示发送，false表示不发送），此处为示例，实际应用中需要更换为其他值

allow_ports = 100-200,800-900,1000-3000,3001,3003,4000-50000   # 允许使用的端口范围列表（多个范围之间用逗号分隔），此处允许的端口范围较广，实际应用中可根据需求进行调整

