# //frps.ini
[common]
bind_port = 7000 # 服务端监听的端口，客户端需要连接这个端口
token = q-org # 服务端和客户端之间的认证密钥，需要保持一致
bind_addr = 0.0.0.0 # 服务端绑定的地址，0.0.0.0 表示所有地址
vhost_http_port = 180 # 服务端用于接收 HTTP 请求的端口，可以通过这个端口访问内网的 HTTP 服务

#vhost_https_port = 8443 # 服务端用于接收 HTTPS 请求的端口，可以通过这个端口访问内网的 HTTPS 服务
#subdomain_host = q.qio.wiki # 服务端用于支持子域名访问的域名，如果设置了这个选项，可以通过子域名来访问内网的服务

dashboard_addr = 0.0.0.0 # 服务端仪表盘的地址，0.0.0.0 表示所有地址
dashboard_port = 7500 # 服务端仪表盘的端口，可以通过这个端口访问仪表盘页面

dashboard user and passwd for basic auth protect
dashboard_user = q-org # 仪表盘的用户名，用于登录仪表盘
dashboard_pwd = q-org # 仪表盘的密码，用于登录仪表盘

dashboard TLS mode
dashboard_tls_mode = false # 是否启用仪表盘的 TLS 模式，如果为 true，则需要提供证书和密钥文件

dashboard_tls_cert_file = server.crt # 仪表盘的 TLS 证书文件路径
dashboard_tls_key_file = server.key # 仪表盘的 TLS 密钥文件路径
log_file = ../logs/frps.log # 日志文件的路径，如果为 console，则输出到控制台

trace, debug, info, warn, error
log_level = info # 日志级别，从低到高分为 trace, debug, info, warn, error

log_max_days = 3 # 日志文件保留的最大天数

disable log colors when log_file is console, default is false
disable_log_color = false # 是否禁用日志颜色，当日志输出到控制台时，可以设置为 true

DetailedErrorsToClient defines whether to send the specific error (with debug info) to frpc. By default, this value is true.
detailed_errors_to_client = true # 是否将具体的错误信息（包含调试信息）发送给客户端，默认为 true

allow_ports = 100-200,800-900,1000-3000,3001,3003,4000-50000 # 允许客户端使用的远程端口范围，可以使用逗号分隔多个范围或单个值
